name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        source-url: https://nuget.pkg.github.com/Jvs34/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build Gmad.Shared/Gmad.Shared.csproj --configuration Release
    - name: Create the packages
      run: dotnet pack --configuration Release
    - name: Publish the package to GPR
      run: dotnet nuget push *.nupkg
